export {
  FAVORITES_SCHEMA_VERSION,
  FAVORITES_STORAGE_KEY,
  LEGACY_FAVORITE_MAPS_KEY,
  LEGACY_FAVORITE_PLAYERS_KEY,
  addMapFavorite,
  addPlayerFavorite,
  clearFavorites,
  createFavoriteStore,
  decodeFavoritesDocument,
  favoriteKey,
  favoriteStore,
  hasFavorite,
  migrateLegacyFavorites,
  parseFavoritesDocument,
  removeFavorite,
  selectMapFavorites,
  selectPlayerFavorites,
  toggleMapFavorite,
  togglePlayerFavorite,
  useFavorites,
} from "./favorites";
export type {
  FavoriteEntityType,
  FavoriteEntry,
  FavoriteKey,
  FavoriteMapSnapshot,
  FavoritePlayerSnapshot,
  FavoriteStore,
  FavoriteStoreOptions,
  FavoritesDocumentV1,
  MapFavorite,
  PlayerFavorite,
} from "./favorites";
